apiVersion: v1
kind: Service
metadata:
  name: book-microservice-loadbalancer
spec:
  selector:
    app: book-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 50051
  type: LoadBalancer