apiVersion: v1
kind: Service
metadata:
  name: magazine-microservice-loadbalancer
spec:
  selector:
    app: magazine-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 50052
  type: LoadBalancer