apiVersion: v1
kind: Service
metadata:
  name: audiovisual-microservice-nodeport
spec:
  selector:
    app: audiovisual-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 50053
  type: NodePort